---
version: '3.4'
services:

  influxdb:
    image: "influxdb:1.8"
    ports:
      - "8086:8086"
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      start_period: 5s
    environment:
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=venus
      - INFLUXDB_ADMIN_PASSWORD=s3cr4t

  timescaledb:
    image: "timescale/timescaledb:latest-pg15"
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: timescaledb/setup_venus_db.sh
        target: /docker-entrypoint-initdb.d/999_setup_venus_db.sh
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      timeout: 10s
      start_period: 5s
    environment:
      - POSTGRES_PASSWORD=s3cr4t

  grafana:
    image: "grafana/grafana:9.3.8"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: grafana/provisioning
        target: /provisioning
    environment:
      - GF_LOG_MODE=console
      - GF_INSTALL_PLUGINS=simpod-json-datasource
      - GF_PATHS_PROVISIONING=/provisioning
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/provisioning/dashboards/venus-devices.json
      - VGS_INFLUXDB_URL=http://host.docker.internal:8086
      - VGS_INFLUXDB_USERNAME=venus
      - VGS_INFLUXDB_PASSWORD=s3cr4t
      - VGS_TIMESCALEDB_URL=host.docker.internal:5432
      - VGS_TIMESCALEDB_USERNAME=venus
      - VGS_TIMESCALEDB_PASSWORD=s3cr4t
    depends_on:
      influxdb:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
