apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: datasource-timescaledb
    type: postgres
    access: proxy
    url: ${VGS_TIMESCALEDB_URL}
    user: ${VGS_TIMESCALEDB_USERNAME}
    database: venus
    secureJsonData:
      password: ${VGS_TIMESCALEDB_PASSWORD}
    jsonData:
      database: venus
      sslmode: 'disable'
      postgresVersion: 10000
      timescaledb: true

